--!strict
--[[
	Guard
	Argument validators for remotes. Each returns a function (value) -> boolean.
	Net runs them before any handler, so handlers only ever see well-formed input.
	Never trust anything a client sends: prices, IDs and positions are looked up or
	recomputed on the server, these checks only reject garbage early.
]]

local ReplicatedStorage = game:GetService("ReplicatedStorage")

local CreatureData = require(ReplicatedStorage:WaitForChild("Shared"):WaitForChild("CreatureData"))

export type Validator = (value: any) -> boolean

local Guard = {}

local function isFinite(n: number): boolean
	return n == n and n ~= math.huge and n ~= -math.huge
end

function Guard.number(min: number, max: number): Validator
	return function(value: any): boolean
		return type(value) == "number" and isFinite(value) and value >= min and value <= max
	end
end

function Guard.integer(min: number, max: number): Validator
	return function(value: any): boolean
		return type(value) == "number" and isFinite(value) and value % 1 == 0 and value >= min and value <= max
	end
end

function Guard.boolean(): Validator
	return function(value: any): boolean
		return type(value) == "boolean"
	end
end

-- A plain string no longer than maxLength bytes and without control characters.
function Guard.string(maxLength: number): Validator
	return function(value: any): boolean
		return type(value) == "string" and #value <= maxLength and not value:find("[%c]")
	end
end

function Guard.oneOf(options: { string }): Validator
	local set: { [string]: boolean } = {}
	for _, option in options do
		set[option] = true
	end
	return function(value: any): boolean
		return type(value) == "string" and set[value] == true
	end
end

-- Creature instance ids are short alphanumeric strings generated by the server.
function Guard.uid(): Validator
	return function(value: any): boolean
		return type(value) == "string" and #value > 0 and #value <= 40 and value:match("^[%w%-]+$") ~= nil
	end
end

function Guard.creatureId(): Validator
	return function(value: any): boolean
		return CreatureData.isValidId(value)
	end
end

-- An array of `min`..`max` values that all pass `inner`, with no other keys.
function Guard.list(inner: Validator, min: number, max: number): Validator
	return function(value: any): boolean
		if type(value) ~= "table" then
			return false
		end
		local count = 0
		for key, item in value do
			count += 1
			if type(key) ~= "number" or key ~= count or not inner(item) then
				return false
			end
		end
		return count >= min and count <= max
	end
end

function Guard.optional(inner: Validator): Validator
	return function(value: any): boolean
		return value == nil or inner(value)
	end
end

return table.freeze(Guard)
